language: scala

jdk: oraclejdk11

scala: 2.12.8

script:
  - sbt ++$TRAVIS_SCALA_VERSION -Dpackaging.type=jar test

cache:
  directories:
    - $HOME/.coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -delete
  - find $HOME/.sbt        -name "*.lock"               -delete